# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ZHAO20060708"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/497566236"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "netease music"
name = "Netease Music"
url = "https://music.163.com/#/user/home?id=1552856187"

[social.params]
icon = "brand-netease-music"

[[social]]
identifier = "outlook"
name = "Outlook"
url = "mailto:zhaojiale20060708@outlook.com"

[social.params]
icon = "brand-office"